#-----------------------------------------------------------------------------
# Dataset
dataset_config:
    data_path: # /path/to/dataset
    image_size: # [width, height]

#-----------------------------------------------------------------------------
# Training Parameters
out_path: # /path/to/out

model_config:
    weight_div: # parameter to divide the weights by multiple of 2
    double_layer: # parameter to double the conv layers of unet
    learning_rate: # Learning rate

train_config:
    batch_size: # batch size during training
    apply_aug: # True/False to apply augmentation

    train_epoch: # # of epoch to run training
    train_steps: # # of steps for train set
    val_steps: # # of steps for validation set
    test_steps: # # of steps for test set

    train_iterations: # Number of iterative training to do

eval_config:
    train_steps: # of steps to run for evaluating train set
    val_steps: # of steps to run for evaluating val set
    test_steps: # of steps to run for evaluating test set