#-----------------------------------------------------------------------------
# Dataset
dataset_config:
    data_path: /home/ubuntu/dataset/seg_teeth_v3
    image_size: [496, 352]

#-----------------------------------------------------------------------------
# Training Parameters
out_path: /home/ubuntu/output/seg_model_v3_0726_jacc

model_config:
    weight_div: 2
    double_layer: True
    learning_rate: 1e-5

train_config:
    batch_size: 1
    apply_aug: False

    train_epoch: 100
    train_steps: 20
    val_steps: 50

    train_iterations: 3

eval_config:
    train_steps: 6533
    val_steps: 1097
    test_steps: 275
