#-----------------------------------------------------------------------------
# Dataset
dataset_config:
    data_path: /home/ubuntu/dataset/seg_teeth_eq_v2
    image_size: [496, 352]

#-----------------------------------------------------------------------------
# Training Parameters
out_path: /home/ubuntu/output/seg_model_07_24_bug

model_config:
    weight_div: 2
    double_layer: False
    learning_rate: 1e-4

train_config:
    batch_size: 2
    apply_aug: True

    train_epoch: 100 # 100
    train_steps: 400 # 3839
    val_steps: 100 # 719

    train_iterations: 3

eval_config:
    train_steps: 3839
    val_steps: 719
    test_steps: 239
