#-----------------------------------------------------------------------------
# Dataset
dataset_config:
    data_path: /home/jung/dataset/seg_teeth_v2
    image_size: [496, 352]

#-----------------------------------------------------------------------------
# Training Parameters
train_config:
    out_path: /home/jung/output/seg_teeth_unit

    weight_div: 2
    double_layer: False

    batch_size: 1

    apply_aug: False

    train_epoch: 5
    train_steps: 1
    val_steps: 1
    test_steps: 1

    learning_rate: 1e-5
