# Dataset Stuff -------------------------------------------------

dataset_config:
  data_path: /home/jung/dataset/seg_teeth_v2
  output_path: ~/output

  # Image [Height, Width]
  image_size: [496, 352]

# Training Hyperparams --------------------------------------

batch_size: 128
num_epochs: 200s