#-----------------------------------------------------------------------------
# Dataset
dataset_config:
    data_path: /home/jung/dataset/seg_teeth_v3_unit
    image_size: [496, 352]

#-----------------------------------------------------------------------------
# Training Parameters
out_path: /home/jung/output/unit_test

model_config:
    weight_div: 2
    double_layer: False
    learning_rate: 1e-4

train_config:
    batch_size: 1
    apply_aug: False

    train_epoch: 5
    train_steps: 2
    val_steps: 2
    test_steps: 2

    train_iterations: 3

eval_config:
    train_steps: 2
    val_steps: 2
    test_steps: 2
