#-----------------------------------------------------------------------------
# Dataset
dataset_config:
    data_path: /home/ubuntu/dataset/seg_teeth_eq_v2
    image_size: [496, 352]

#-----------------------------------------------------------------------------
# Training Parameters
train_config:
    out_path: /home/ubuntu/output/seg_model

    weight_div: 2
    double_layer: False

    batch_size: 1

    apply_aug: True

    train_epoch: 5 # 100
    train_steps: 3839 # 3839
    val_steps: 719 # 719
    test_steps: 293 # 293

    learning_rate: 1e-4

    train_iterations: 3